---
- name: Determine the version of OpenSSH
  ansible.builtin.command:
    cmd: ssh -V
  changed_when: false
  register: ssh_version

- name: Set facts for OpenSSH and OpenSSL versions
  ansible.builtin.set_fact:
    openssh_version: "{{ ssh_version.stderr | regex_search('^OpenSSH_([^,]*)p.*, OpenSSL ([^\ ]*)\ +.+$', '\\1') | first }}"
    openssl_version: "{{ ssh_version.stderr | regex_search('^OpenSSH_([^,]*)p.*, OpenSSL ([^\ ]*)\ +.+$', '\\2') | first }}"

- name: Ensure that a directory for sshd config fragments exists
  ansible.builtin.file:
    group: root
    mode: 0755
    owner: root
    path: /etc/ssh/sshd_config.d
    state: directory

- name: >
    Make sure that sshd_config includes the files in the fragments
    directory
  ansible.builtin.lineinfile:
    firstmatch: yes
    # The Include directive must go at the top of the config file, so
    # we want to place the line before the first non-comment line.
    insertbefore: ^[^#\n]
    line: Include /etc/ssh/sshd_config.d/*.conf
    path: /etc/ssh/sshd_config

- name: Modify sshd's configuration to allow RSA keys
  block:
    - name: Allow RSA keys (OpenSSH < 8.5)
      ansible.builtin.copy:
        content: |
          HostKeyAlgorithms +ssh-rsa
          PubkeyAcceptedKeyTypes +ssh-rsa
        dest: /etc/ssh/sshd_config.d/99-allow-rsakeys.conf
        group: root
        mode: 0644
        owner: root
      when: openssh_version is version("8.5", "<")
    - name: Allow RSA keys (OpenSSH >= 8.5)
      ansible.builtin.copy:
        content: |
          HostKeyAlgorithms +ssh-rsa
          PubkeyAcceptedAlgorithms +ssh-rsa
        dest: /etc/ssh/sshd_config.d/99-allow-rsakeys.conf
        group: root
        mode: 0644
        owner: root
      when: openssh_version is version("8.5", ">=")
